name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  host:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Build
        run: cargo build --verbose

      - name: Run Rustfmt
        run: cargo fmt -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --workspace

      - name: Run Tests
        run: RUST_BACKTRACE=1 cargo test --all-targets --workspace --verbose

  cross:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libudev-dev binutils

      - name: Set up ESP toolchain
        uses: ./.github/actions/esp-toolchain

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build agent for all targets
        run: cargo xtask build agent

  examples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: >
          sudo apt-get update && sudo apt-get install -y
          libudev-dev binutils git cmake ninja-build python3-pip

      - name: Set up ESP toolchain
        uses: ./.github/actions/esp-toolchain

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            . -> target
            examples/rust -> examples/rust/target

      - name: Cache ESP-IDF
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif/frameworks
            ~/.espressif/esp-idf
            ~/.espressif/tools
            ~/.espressif/python_env
          key: ${{ runner.os }}-espressif-${{ hashFiles('examples/rust/.cargo/config.toml') }}

      - name: Build examples
        run: cargo xtask build examples
